# Project information
site_name: 'College Assignments'
site_description: 'A guide on certain complex college assignments'
site_url: 'https://docs.soyabn09.gq'

# Copyright
copyright: '&copy; 2020 Soyab Nandhla'

# Configuration
docs_dir: 'docs'
theme:
  name: 'material'
  language: 'en'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: true
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  #favicon: 'https://freemcserver.net/img/logo.png'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

# Extensions
markdown_extensions:
  - toc:
      permalink: ""
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search

# Customization
extra:
  search:
    language: 'en'

# Page tree
nav:
  - Home: index.md
  - U27.1:
    - Introduction: U27/index.md